apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: webapp
spec:
  selector:
    app: employee
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

